### ISSUE TITLE
Does not work whe searching in browser

### ISSUE THREAD

**Issue by DoctorToBeIn23** [jefdongus/insert-symbols-anki-addon#10]
First one I tried was beta and it inserted a "B" in but when I do it on a card it does the true symbol.

**Comment by jefdongus** [comment]
Just to clarify, you typed `:beta:` in the search bar replacement _did occur_, but the result was a "B" and not "β"? 

It'd be helpful to know the following:
1. What happens if you try typing other symbols, eg. `:Delta:` or `:Sigma:`?
2. Are you using the latest version of the add-on?

**Comment by DoctorToBeIn23** [comment]
Seems to be working now, must have been me

**Comment by jefdongus** [comment]
No problem, let me know if something else pops up!
