### ISSUE TITLE
Very problematic error with undo

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [jefdongus/insert-symbols-anki-addon#11]
Hi,

I am seeing some confusing behavior and thought you should know about it.

Here's a string : `abcdefg`

if I type ::c:: then SAYT automatically replaces it with `}}{{c1::`, it helps me separating clozes.

Now, let's say I put my cursor between a and b, like so (_ indicates cursor position) : `a_bcdefg` with no space or anything else, and type ::c:: I get this `a}}{{c1::bcdefg` which is expected behavior.

Now, if I had my cursor at the wrong position and want to undo, here's what ctrl+z does : `a}}{{cg` (1st ctrl+Z) then `ag` (2nd ctrl+Z) and if I undo the undo (ctrl+shift+Z) I get `a}}{{c1::g` and can't go further.

So first issue, the undo doesn't go back to what was just before, second issue : I can't actually undo back to my original sentence which seems forever lost.

I lost several sentence this way and would be very grateful if you found a fix.

Thanks a lot!

**Comment by jefdongus** [comment]
So it turns out the Anki 2.1 WebView stores something akin to user actions (insert X characters, delete Y characters, etc.) in the undo history, but HTML insertion/deletion wasn't getting recorded, hence the funky behavior with undo. 

Try the new update -- hopefully this fixes #12 as well.

**Comment by thiswillbeyourgithub** [comment]
You fixed both of my issues with this, thanks A LOT! :)
