### ISSUE TITLE
Problem entering html inside an italic string

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [jefdongus/insert-symbols-anki-addon#12]
Hi,
another problem that seems to be related to #11 . 

If I have `abcdefg` and put my cursor after `c` and enter `::c::` which should be replaced with `}}{{c1::` I end up with `abc::c::}}{{c1::defg`

Also happens with bold.

Looking at the html I have : `<b>abc::c::</b>}}{{c1::<b>defg</b>`

So the \<b> marker seems to stop SAYT when it tries to remove `::c::`

**Comment by jefdongus** [comment]
Haven't been able to recreate this error (I only tried testing after the bug fix in #11)... so hopefully that fixed it?

**Comment by thiswillbeyourgithub** [comment]
I'm confirming you fixed this :)
