### ISSUE TITLE
Problem with 2.1.50

### ISSUE THREAD

**Issue by drkevko** [jefdongus/insert-symbols-anki-addon#35]
Hey! First of all: I've been saving hours of typing because of this add on and I absolutely love it.

However, in Anki 2.1.50, Symbols don't get replaced anymore. Neither in the editor nor in the browser. 

I hope you can find the time to take a look at this. This add on is a must.

Thanks in advance :)

**Comment by itsdomme** [comment]
It doesn't work in 2.1.51 either

**Comment by jefdongus** [comment]
This has been updated by a contributor! Sorry, the pull request didn't show up in my email somehow :(
