### ISSUE TITLE
Feature suggestion: Add symbols in the browser

### ISSUE THREAD

**Issue by AnKingMed** [jefdongus/insert-symbols-anki-addon#4]
Would it be possible to add symbols while typing in the browser? That would make it much easier to search for cards using those symbols

**Comment by jefdongus** [comment]
Quick update: I looked into it, and it looks like the search bar in the browser uses completely different code than the editor. So it's doable, but not completely trivial... in other words, give me a bit of time :)

**Comment by AnKingMed** [comment]
Awesome! I really appreciate it!  I'm planning on making a video on this on my youtube channel in the future if possible :)

**Comment by jefdongus** [comment]
Ok, this _should_ work in the latest update. Please let me know if you run into any bugs! I'll leave this open for a bit.

**Comment by thiswillbeyourgithub** [comment]
I have bugs :)!
```
Debug info:
Anki 2.1.21 (f1734a47) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-03-10 17:22:16
Add-ons possibly involved: Symbols As You Type

Caught exception:
Traceback (most recent call last):
  File "/home/USER/.local/share/Anki2/addons21/2040501954/browser_replacer.py", line 28, in on_return_pressed
    current_text = self._search_box.text()
RuntimeError: wrapped C/C++ object of type QLineEdit has been deleted
```

**Comment by jefdongus** [comment]
Hmm... can you think of what actions you did immediately before the error appeared? I think the error is suggesting that the search bar in the browser had been deleted (and perhaps re-created?), and I'm not sure what would cause that. Any more info would be much appreciated!

**Comment by thiswillbeyourgithub** [comment]
Well i tend to leave the browse window open and use the add card window a lot. This bugs sometimes arrives even when i have not been using the browse window at all for a while.

**Comment by jefdongus** [comment]
Hm, still not sure why exactly this is happening, but I tried changing the reference to the search bar so that hopefully it doesn't point to an old/expired copy. Let me know if you still get the error.
