### ISSUE TITLE
Error while trying to close card browser

### ISSUE THREAD

**Issue by Ram1532** [jefdongus/insert-symbols-anki-addon#49]
Error with following message occurs when I try to close card browser:

"Anki encountered a problem. Please follow the troubleshooting steps.

Add-ons possibly involved: ⁨Symbols As You Type⁩"

This problem occurs only when I try to close browser when it didn't show any cards in current browsing session. For example, if I open card browser with empty deck selected and then try to close it, error shows up. But if I enter a query and browser finds any cards, and then I press the close button, browser closes normally. If browser showed cards and then I enter query with zero result, browser closes normally too.

Debug info:

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.browser.browser", line 358, in _closeWindow
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "D:\Users\Admin\AppData\Roaming\Anki2\addons21\2040501954\insert_symbols.py", line 117, in on_editor_cleanup
    ins_sym_webview_owners['editors'].remove(editor)
ValueError: list.remove(x): x not in list

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Add Table ['1237621971', 2023-06-18T16:37, 'None', mod]
Button Colours Good Again ['2494384865', 2022-09-27T15:18, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T12:15, 'None', '']
Remove card history ['2089200096', 2023-10-19T08:15, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T06:43, 'None', '']
Symbols As You Type ['2040501954', 2024-01-05T07:33, 'None', '']

===IDs of active AnkiWeb add-ons===
1237621971 1374772155 1771074083 2040501954 2089200096 2494384865

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by jefdongus** [comment]
Should be fixed
