### ISSUE TITLE
feature suggestion : using this to make macros

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [jefdongus/insert-symbols-anki-addon#5]
Hi,

I'd like to use your great addon to make macros, for example I very often have to enter a sequence of keys to add this :
![screenshot](https://user-images.githubusercontent.com/26625900/74866201-60816700-534a-11ea-8cc2-6b4d41eb694d.png)

The corresponding characters for this are : 
`<div>{{c1::</div><div><ul><li><br></li></ul></div><div>}}<br></div>`

But your addon replaces every < with &lt and > with &gt. Would you be interested in changing this behavior ?

Thanks !

**Comment by thiswillbeyourgithub** [comment]
No opinions :)?

**Comment by jefdongus** [comment]
Hey, sorry haven't had a chance to work on this project until now. So the issue I'm worried about is that most users probably don't know HTML, so if `<` and `>` characters don't get escaped (converted to `&lt;` and `&gt;`) by default, the plugin would be non-intuitive to use / break for the users who want < and > to show up on the card.

Perhaps a future step would be to add special code blocks which would be delimited by a special set of characters, but that could also cause problems for users who happen to use those as keys. I'm open to suggestions!

**Comment by thiswillbeyourgithub** [comment]
Hi, thanks for the answer.

What do you think of allowing escaping, so people using `<` and `>` wouldn't see any change but more advanced users could use `\>" to parse html.

basically : if a `<` is preceded with a \ then don't convert it to `&lt;` but only remove the \ : 
`<`    becomes   `&lt;`
`\<`    becomes    `<`

**Comment by jefdongus** [comment]
Upon further thought, having HTML blocks would be better since that would be a more flexible approach (some other users have mentioned wanting super/subscripts for example). I'll put it on the to-do list, but it'll probably take a couple of weeks or so for me to get to it.

**Comment by thiswillbeyourgithub** [comment]
Thanks, that would be incredible as it could allow for endless macros!

Also do you accept (small) donations ? I might be interested if it incentivises you :)

**Comment by jefdongus** [comment]
No need for donations :) Since I'm a medical student, the limiting factor really is just time!

**Comment by thiswillbeyourgithub** [comment]
I am as well so I understand. Thanks anyway!

**Comment by jefdongus** [comment]
Ok, this should work now! Please let me know if you run into any bugs.

**Comment by thiswillbeyourgithub** [comment]
I missed your message, sorry!

I am not sure I understand, you did the modifications and allow for macros ? If yes I don't understand how I'm supposed to do it.
