### ISSUE TITLE
any reason for why we can't use spaces ?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [jefdongus/insert-symbols-anki-addon#6]
Hi,

I just tried to add symbols (or more like macros I guess) to accelerate indentation, for example : 
`:t:` -> `    ` (that's four spaces but github formats them) or even `: :` -> `    ` but the add button stays grey.

Any reasons for this ? I think this addon could become indispensable if it included things like that :)

**Comment by jefdongus** [comment]
This is now supported in the latest update.
